#!/bin/sh
# This file is autogenerated - DO NOT EDIT!
set -euo pipefail
BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="${BASE_DIR}/.."
(
cd ${REPO_DIR}
helm uninstall af-mysql -n airflow
kubectl delete po --all -n airflow
kubectl delete pvc --all -n airflow
kubectl delete -f airflow/rbac.yaml -n airflow
kubectl delete namespace airflow
)
